# Generated by Django 3.2.5 on 2021-08-31 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secteur_professionnel', models.CharField(blank=True, max_length=150, null=True)),
                ('grade', models.CharField(blank=True, max_length=100, null=True)),
                ('Type_ACT_MLD', models.CharField(blank=True, choices=[(0, 'ACT'), (1, 'MLD')], max_length=3, null=True)),
                ('mode_début', models.CharField(choices=[('brutal', 'brutal'), ('non précisé', 'non précisé')], max_length=11)),
                ('mécanisme', models.CharField(blank=True, max_length=150, null=True)),
                ('lombalgies', models.CharField(default='oui', max_length=3)),
                ('sciatalgie', models.CharField(default='non', max_length=13)),
                ('diabète', models.CharField(default=0, max_length=3)),
                ('HTA', models.CharField(blank=True, default=0, max_length=3, null=True)),
                ('respiratoire', models.CharField(blank=True, default=0, max_length=150, null=True)),
                ('Autre_1', models.CharField(blank=True, default=0, max_length=250, null=True)),
                ('mariage', models.CharField(choices=[('oui', 'oui'), ('non', 'non'), ('divorcé', 'divorcé(é)'), ('veuve', 'veuve')], max_length=7)),
                ('nombre_enfants', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('scolarisation', models.CharField(blank=True, max_length=150, null=True)),
                ('rééducation', models.CharField(blank=True, max_length=150, null=True)),
                ('état_général', models.CharField(blank=True, max_length=150, null=True)),
                ('coopérant', models.CharField(blank=True, max_length=150, null=True)),
                ('poids', models.CharField(blank=True, max_length=150, null=True)),
                ('taille', models.CharField(blank=True, max_length=150, null=True)),
                ('IMC', models.CharField(blank=True, max_length=150, null=True)),
                ('corpulence', models.CharField(blank=True, max_length=150, null=True)),
                ('ceinture_de_soutien', models.CharField(blank=True, max_length=150, null=True)),
                ('boiterie', models.CharField(blank=True, max_length=150, null=True)),
                ('déroulement_du_pas', models.CharField(blank=True, max_length=150, null=True)),
                ('droit', models.CharField(blank=True, max_length=150, null=True)),
                ('gauche', models.CharField(blank=True, max_length=150, null=True)),
                ('sur_les_talons', models.CharField(blank=True, max_length=150, null=True)),
                ('sur_les_pointes_des_pieds', models.CharField(blank=True, max_length=150, null=True)),
                ('mode', models.CharField(blank=True, max_length=150, null=True)),
                ('stabilité', models.CharField(blank=True, max_length=150, null=True)),
                ('droit_1', models.CharField(blank=True, max_length=150, null=True)),
                ('gauche_1', models.CharField(blank=True, max_length=150, null=True)),
                ('cicatrice', models.CharField(blank=True, max_length=150, null=True)),
                ('ROT', models.CharField(blank=True, max_length=150, null=True)),
                ('age', models.PositiveSmallIntegerField(blank=True, null=True)),
            ],
        ),
    ]
