# Generated by Django 3.2.5 on 2021-08-31 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predict', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='droit_1',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='gauche_1',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='grade',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='mécanisme',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='scolarisation',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='secteur_professionnel',
        ),
        migrations.AlterField(
            model_name='patient',
            name='Autre_1',
            field=models.CharField(choices=[(0, 'NONE'), (1, '#depression '), (2, '##hyo '), (3, '##pso '), (4, '##vit '), (5, '#ary'), (6, '#osté')], max_length=250),
        ),
        migrations.AlterField(
            model_name='patient',
            name='HTA',
            field=models.CharField(choices=[(1, 'oui'), (0, 'non')], max_length=3),
        ),
        migrations.AlterField(
            model_name='patient',
            name='IMC',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='patient',
            name='ROT',
            field=models.CharField(choices=[(1, 'normaux'), (2, 'rotuiliens abolis achilééens normaux'), (3, 'rotuliens abolis'), (4, 'abolis à gauche'), (5, 'rotulien droit aboli')], max_length=150),
        ),
        migrations.AlterField(
            model_name='patient',
            name='Type_ACT_MLD',
            field=models.CharField(choices=[(1, 'ACT'), (0, 'MLD')], max_length=3),
        ),
        migrations.AlterField(
            model_name='patient',
            name='age',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='patient',
            name='boiterie',
            field=models.CharField(choices=[(0, 'non'), (1, 'Bil'), (2, 'gauche'), (3, 'droit')], max_length=150),
        ),
        migrations.AlterField(
            model_name='patient',
            name='ceinture_de_soutien',
            field=models.CharField(choices=[(1, 'oui'), (0, 'non')], max_length=3),
        ),
        migrations.AlterField(
            model_name='patient',
            name='cicatrice',
            field=models.CharField(choices=[(1, 'oui'), (0, 'non')], max_length=150),
        ),
        migrations.AlterField(
            model_name='patient',
            name='coopérant',
            field=models.CharField(choices=[(1, 'oui'), (0, 'non'), (2, 'peu')], max_length=150),
        ),
        migrations.AlterField(
            model_name='patient',
            name='corpulence',
            field=models.CharField(choices=[(1, 'normale'), (2, 'obésité modérée'), (3, 'surpoids'), (4, 'obésité sévère'), (5, 'maigre'), (6, 'obésité morbide'), (7, 'insuffisance pondérale')], max_length=150),
        ),
        migrations.AlterField(
            model_name='patient',
            name='diabète',
            field=models.CharField(choices=[(1, 'oui'), (0, 'non')], max_length=2),
        ),
        migrations.AlterField(
            model_name='patient',
            name='droit',
            field=models.CharField(choices=[(1, '#stable'), (0, '#instable'), (2, '#gene')], max_length=150),
        ),
        migrations.AlterField(
            model_name='patient',
            name='déroulement_du_pas',
            field=models.CharField(choices=[(1, 'complet'), (0, 'incomplet')], max_length=150),
        ),
        migrations.AlterField(
            model_name='patient',
            name='gauche',
            field=models.CharField(choices=[(1, '#stable'), (0, '#instable'), (2, '#gene')], max_length=150),
        ),
        migrations.AlterField(
            model_name='patient',
            name='lombalgies',
            field=models.CharField(choices=[(1, 'oui'), (0, 'non')], max_length=2),
        ),
        migrations.AlterField(
            model_name='patient',
            name='mariage',
            field=models.CharField(choices=[(1, 'oui'), (0, 'non'), (3, 'divorcé(é)'), (4, 'veuve')], max_length=7),
        ),
        migrations.AlterField(
            model_name='patient',
            name='mode',
            field=models.CharField(choices=[(1, '#complet'), (0, '#incomplet'), (2, '#impossible')], max_length=150),
        ),
        migrations.AlterField(
            model_name='patient',
            name='mode_début',
            field=models.CharField(choices=[(1, 'brutal'), (0, 'non précisé')], max_length=11),
        ),
        migrations.AlterField(
            model_name='patient',
            name='poids',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='patient',
            name='respiratoire',
            field=models.CharField(choices=[(1, 'BPCO'), (2, '#asthme'), (3, '#tuberculose'), (4, '#DDB')], max_length=150),
        ),
        migrations.AlterField(
            model_name='patient',
            name='rééducation',
            field=models.CharField(choices=[(1, 'oui'), (0, 'non')], max_length=150),
        ),
        migrations.AlterField(
            model_name='patient',
            name='sciatalgie',
            field=models.CharField(choices=[(1, 'oui'), (0, 'non')], max_length=2),
        ),
        migrations.AlterField(
            model_name='patient',
            name='stabilité',
            field=models.CharField(choices=[(1, '#stable'), (0, '#instable'), (2, '#gene'), (3, '#impossible')], max_length=150),
        ),
        migrations.AlterField(
            model_name='patient',
            name='sur_les_pointes_des_pieds',
            field=models.CharField(choices=[(1, '#pos'), (0, '#instable'), (2, '#gene'), (3, '#impossible')], max_length=150),
        ),
        migrations.AlterField(
            model_name='patient',
            name='sur_les_talons',
            field=models.CharField(choices=[(1, '#pos'), (0, '#instable'), (2, '#gene'), (3, '#impossible')], max_length=150),
        ),
        migrations.AlterField(
            model_name='patient',
            name='taille',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='patient',
            name='état_général',
            field=models.CharField(choices=[(1, 'bon'), (0, 'moyen')], max_length=150),
        ),
    ]
