# Generated by Django 3.2.5 on 2021-07-28 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthcare', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='mode_début',
            field=models.CharField(choices=[('brutal', 'brutal'), ('non précisé', 'non précisé')], max_length=11),
        ),
    ]
