# Generated by Django 3.2.5 on 2021-07-29 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthcare', '0003_auto_20210729_0144'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='add',
        ),
        migrations.AddField(
            model_name='user',
            name='is_Expert',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_conseil',
            field=models.BooleanField(default=False),
        ),
    ]
