# Generated by Django 3.2.5 on 2021-07-30 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('healthcare', '0008_alter_patient_durée_cotisation_an'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='docteur',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='expert',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_Expert',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_conseil',
        ),
    ]
