# Generated by Django 3.2.5 on 2021-07-31 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthcare', '0009_auto_20210730_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='date_expertise',
            field=models.DateField(blank=True, null=True, verbose_name='date expertise'),
        ),
    ]
