# Generated by Django 3.2.5 on 2021-07-31 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthcare', '0010_alter_patient_date_expertise'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='cin',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
