# Generated by Django 3.2.5 on 2021-07-31 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthcare', '0011_alter_patient_cin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='Type_ACT_MLD',
            field=models.CharField(blank=True, choices=[('ACT', 'ACT'), ('MLD', 'MLD')], max_length=3, null=True),
        ),
    ]
