# Generated by Django 3.2.5 on 2021-07-31 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthcare', '0013_auto_20210731_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='cin',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='matricule',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
