# Generated by Django 3.2.5 on 2021-07-31 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthcare', '0014_auto_20210731_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='matricule',
            field=models.TextField(blank=True, null=True),
        ),
    ]
