# Generated by Django 3.2.5 on 2021-07-31 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthcare', '0017_alter_patient_matricule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='respiratoire',
            field=models.CharField(blank=True, default=0, max_length=150, null=True),
        ),
    ]
