# Generated by Django 3.2.5 on 2021-08-02 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthcare', '0019_auto_20210731_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='sciatalgie',
            field=models.CharField(default='non', max_length=13),
        ),
    ]
